// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Przyklady_pojedyncze;

namespace Przyklady_pojedyncze.Migrations
{
    [DbContext(typeof(WynikiA))]
    [Migration("20191023200519_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Przyklady_pojedyncze.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GradeValue")
                        .HasColumnType("TEXT");

                    b.HasKey("GradeId");

                    b.ToTable("Wyniki");
                });
#pragma warning restore 612, 618
        }
    }
}
